# -------------------------------
# MapProxy example configuration.
# -------------------------------
#
# This is a minimal MapProxy configuration.
# See full_example.yaml and the documentation for more options.
#

# Starts the following services:
# Demo:
#     http://localhost:8080/demo
# WMS:
#     capabilities: http://localhost:8080/service?REQUEST=GetCapabilities
# WMTS:
#     capabilities: http://localhost:8080/wmts/1.0.0/WMTSCapabilities.xml
#     first tile: http://localhost:8080/wmts/osm/webmercator/0/0/0.png
# Tile service (compatible with OSM/etc.)
#     first tile: http://localhost:8080/tiles/osm/webmercator/0/0/0.png
# TMS:
#     note: TMS is not compatible with OSM/Google Maps/etc.
#     fist tile: http://localhost:8080/tms/1.0.0/osm/webmercator/0/0/0.png
# KML:
#     initial doc: http://localhost:8080/kml/osm/webmercator

#base: ['base/globals.yaml','base/sourcesgd.yaml','base/servicewmsgd.yaml']
base: ['base/globals.yaml','base/grids.yaml']

services:
  demo:
  wms:
    # only offer WMS 1.1.1
    versions: ['1.3.0', '1.1.1']

    # supported SRS for this WMS
    srs: ['EPSG:2056']

    # force the layer extents (BBOX) to be displayed in this SRS
    bbox_srs: ['EPSG:2056']

    # limit the supported image formats.
    image_formats: ['image/jpeg', 'image/png', 'image/gif', 'image/GeoTIFF', 'image/tiff']

    # add attribution text in the lower-right corner.
    attribution:
      text: ''
    #  text: 'Rasterdaten (c) swisstopo, AV-Daten (c) GIS Daten AG'

    # return an OGC service exception when one or more sources return errors
    # or no response at all (e.g. timeout)
    on_source_errors: raise

    # some WMS clients do not send all required parameters in feature info
    # requests, MapProxy ignores these errors unless you set strict to true.
    strict: false

    # list of feature info types the server should offer
    featureinfo_types: ['text', 'xml']

    md:
      # metadata used in capabilities documents
      title: SWISSIMAGE 2021, 10 cm
      abstract: SWISSIMAGE 2021, 10 cm
      online_resource: https://www.gis-daten.ch
      contact:
        organization: GIS Daten AG
        address: Aemaettlistrasse 2
        city: Stans
        postcode: 6370
        country: Switzerland
        phone: +41 (0)41 618 61 12
        email: support@gis-daten.ch
      # multiline strings are possible with the right indention
      access_constraints:
        Dieser WMS darf nur fuer die GIS Daten AG verwendet werden.

    # md:
    #   # metadata used in capabilities documents
    #   title: WMS der Geodaten des Kanton Uri
    #   abstract: WMS der Geodaten des Kanton Uri
    #   online_resource: https://geo.ur.ch/wms?
    #   contact:
    #     organization: Lisag AG
    #     address: Reussacherstrasse 30
    #     city: Altdorf
    #     postcode: 6460
    #     country: Switzerland
    #     phone: 041 500 60 60
    #     email: mail@lisag.ch
    #   # multiline strings are possible with the right indention
    #   access_constraints:
    #     NONE

  # wmts:
  #   # use restful access to WMTS
  #   restful: true
  #   # this is the default template for MapProxy
  #   restful_template: '/{Layer}/{TileMatrixSet}/{TileMatrix}/{TileCol}/{TileRow}.{Format}'
  #   # and also allow KVP requests
  #   kvp: true
  #   # # only offer WMS 1.1.1
  #   versions: ['1.3.0']

  #   # # supported SRS for this WMS
  #   srs: ['EPSG:2056']

  #   # # force the layer extents (BBOX) to be displayed in this SRS
  #   # bbox_srs: ['EPSG:2056']

  #   # # limit the supported image formats.
  #   image_formats: ['image/png', 'image/jpeg']

  #   # # add attribution text in the lower-right corner.
  #   # attribution:
  #     # text: 'Rasterdaten (c) swisstopo, AV-Daten (c) GIS Daten AG'

  #   # # return an OGC service exception when one or more sources return errors
  #   # # or no response at all (e.g. timeout)
  #   # on_source_errors: raise

  #   # # some WMS clients do not send all required parameters in feature info
  #   # # requests, MapProxy ignores these errors unless you set strict to true.
  #   # strict: false

  #   # # list of feature info types the server should offer
  #   # featureinfo_types: ['text', 'xml']

  #   md:
  #     # metadata used in capabilities documents
  #     title: WMTS Basisdaten GIS Daten AG
  #     abstract: Orthofoto 10cm 2021
  #     online_resource: https://www.gis-daten.ch
  #     contact:
  #       organization: GIS Daten AG
  #       address: Aemaettlistrasse 2
  #       city: Stans
  #       postcode: 6370
  #       country: Switzerland
  #       phone: +41 (0)41 618 61 12
  #       email: support@gis-daten.ch
  #     # multiline strings are possible with the right indention
  #     access_constraints:
  #       Orthofoto 10cm 2021

parts:
    coverages:
        bboxnw: &bboxnw
            bbox: [2643483, 1171738, 2702269, 1216819]
            srs: 'EPSG:2056'
        bboxow: &bboxow
            bbox: [2643483, 1171738, 2702269, 1216819]
            srs: 'EPSG:2056'
        bboxnwow: &bboxnwow
            bbox: [2643483, 1171738, 2702269, 1216819]
            srs: 'EPSG:2056'
        bboxlu: &bboxlu
            bbox: [2630127, 1180568, 2681764, 1237690]
            srs: 'EPSG:2056'
        bboxels: &bboxels
            bbox: [2620000, 1146000, 2724800, 1242000]
            srs: 'EPSG:2056'
        bboxclip: &bboxclip
            bbox: [2660000, 1172000, 2680000, 1200000]
            #datasource: Point(2660000, 1172000).buffer(2000)
            srs: 'EPSG:2056'
        bboxch: &bboxch
            bbox: [2480000, 1062000, 2865000, 1302000]
            srs: 'EPSG:2056'
        bboxuri: &bboxuri
            bbox: [2670000, 1150000, 2717000, 1216819]
            srs: 'EPSG:2056'

layers:
  - name: ch.nw.swissimage-2021
    title: SWISSIMAGE Zeitreise 2021
    sources:
      - ch.nw.swissimage-2021


sources:
  ch.nw.swissimage-2021:
    type: wms
    http:
      ssl_no_cert_checks: true
    req:
      layers: ch.swisstopo.swissimage-product
      url: https://wms.geo.admin.ch/?SERVICE=WMS&VERSION=1.3.0&TIME=2021
      transparent: true
    opts:
      version: 1.3.0
      featureinfo: true
      featureinfo_tolerance: 10
      featureinfo_return_geometries: true
    supported_srs:
      - 'EPSG:2056'
    coverage: *bboxnw

        
# caches:
#   ch.swisstopo.swissimage.cache:
#     grids: [gisdaten_grid2056]
#     # grids: [GLOBAL_WEBMERCATOR]
#     sources: [ch.swisstopo.swissimage]
#     #disable_storage: true
#     #format: mixed
    
#     # request a meta tile, that consists of m x n tiles
#     meta_size: [6, 6]
#     # allow to make 2 parallel requests to the sources for missing tiles
#     concurrent_tile_creators: 16

#     # level 0 - 13 will be cached, others are served directly from the source
#     #use_direct_from_level: 12
#     format: image/jpeg
#     cache:
#       type: compact
#       version: 2
#       directory: //trigopgis04.file.core.windows.net/cache/mapproxy/cache2056/ch.swisstopo.swissimage/_alllayers
# #      type: sqlite
# #      directory: //trigopgis04.file.core.windows.net/cache/mapproxy/ch.swisstopo.swissimage
    
grids:

  localgrid:
    base: GLOBAL_WEBMERCATOR
    srs: EPSG:2056
    bbox: [2643483, 1171738, 2702269, 1216819]
    bbox_srs: EPSG:2056
    # tile_size: [256,256]
    # res: [64, 256, 1024, 4096, 16384]
    min_res: 64
    # res_factor: sqrt2
    
  gisdaten_grid2056:
    #base: GLOBAL_MERCATOR
    srs: EPSG:2056
    bbox: [2480000, 1062000, 2865000, 1302000]
    bbox_srs: EPSG:2056
    origin: 'nw'
    tile_size: [256,256]
    #stretch_factor: 2.1
    #threshold_res: [50]
    #aus schema
    
    res: [66.145965625264594, 39.687579375158755, 26.458386250105836, 13.229193125052918, 6.6145965625264589, 3.9687579375158752, 2.6458386250105836, 1.3229193125052918, 0.79375158750317509, 0.52916772500211673, 0.26458386250105836, 0.13229193125052918, 0.066145965625264591]
    #C:\mapproxy\python\WPy64-3870\python-3.8.7.amd64\Scripts\mapproxy-util.exe scales --unit m --dpi 90.71428571429 --as-res-config 250000 150000 100000 50000 25000 15000 10000     res: [
#    res: [
#         #  res            level     scale @90.7 DPI
#           70.0000000000, #  0      250000.00000000
#           42.0000000000, #  1      150000.00000000
#           28.0000000000, #  2      100000.00000000
#           14.0000000000, #  3       50000.00000000
#            7.0000000000, #  4       25000.00000000
#            4.2000000000, #  5       15000.00000000
#            2.8000000000, #  6       10000.00000000
#            1.4000000000, #  7        5000.00000000
#            0.8400000000, #  8        3000.00000000
#            0.5600000000, #  9        2000.00000000
#            0.2800000000, # 10        1000.00000000
#            0.1400000000, # 11         500.00000000
#            0.0700000000, # 12         250.00000000
#    ]
  #C:\mapproxy\python\WPy64-3870\python-3.8.7.amd64\Scripts\mapproxy-util.exe scales --unit m --dpi 96 --as-res-config  500000 250000 150000 100000 50000 25000 15000 10000 5000 3000 2000 1000 500 250  
#    res: [
#         #  res            level     scale @96.0 DPI
#           66.1458333333, #  0      250000.00000000
#           39.6875000000, #  1      150000.00000000
#           26.4583333333, #  2      100000.00000000
#           13.2291666667, #  3       50000.00000000
#            6.6145833333, #  4       25000.00000000
#            3.9687500000, #  5       15000.00000000
#            2.6458333333, #  6       10000.00000000
#            1.3229166667, #  7        5000.00000000
#            0.7937500000, #  8        3000.00000000
#            0.5291666667, #  9        2000.00000000
#            0.2645833333, # 10        1000.00000000
#            0.1322916667, # 11         500.00000000
#            0.0661458333, # 12         250.00000000
#    ]
   
    #min_res: 64
    # res_factor: sqrt2
    
globals:
  srs:
    axis_order_en: ['EPSG:21781', 'EPSG:2056']
    # override system projection file
    #proj_data_dir: '/path to dir that contains epsg file'

  # cache options
  cache:
    # where to store the cached images
    # base_dir: './cache_data'
    # where to store lockfiles for concurrent_requests
    # lock_dir: './cache_data/locks'
    # where to store lockfiles for tile creation
    # tile_lock_dir: './cache_data/tile_locks'
    base_dir: //trigopgis04.file.core.windows.net/cache/mapproxy
    lock_dir: //trigopgis04.file.core.windows.net/cache/mapproxy/locks
    tile_lock_dir: //trigopgis04.file.core.windows.net/cache/mapproxy/tile_locks


    # request x*y tiles in one step
    meta_size: [4, 4]
    # add a buffer on all sides (in pixel) when requesting
    # new images
    meta_buffer: 80


  # image/transformation options
  image:
    # use best resampling for vector data
    resampling_method: bicubic # nearest/bilinear
    # stretch cached images by this factor before
    # using the next level
    stretch_factor: 1.15
    # shrink cached images up to this factor before
    # returning an empty image (for the first level)
    max_shrink_factor: 4.0

    # Enable 24bit PNG images. Defaults to true (8bit PNG)
    paletted: false
    formats:
      custom_format:
        format: image/png
        # the custom format will be stored as 8bit PNG
        mode: P
        colors: 32
        transparent: true
        encoding_options:
        # The algorithm used to quantize (reduce) the image colors
          quantizer: fastoctree
        opacity:  0.5
      overlay_format:
        format: image/png
        # the custom format will be stored as 8bit PNG
        mode: P
        colors: 32
        transparent: true
        encoding_options:
        # The algorithm used to quantize (reduce) the image colors
          quantizer: fastoctree
        opacity:  0.1
      # edit an existing format
      image/jpeg:
        encoding_options:
          # jpeg quality [0-100]
          jpeg_quality: 85
        
        
        
        
        
        
        
        
        