base:
  - base/globals.yaml
  - base/grids.yaml
services:
  demo: null
  wms:
    versions:
      - 1.3.0
      - 1.1.1
    # supported SRS for this WMS
    srs: ['EPSG:2056','EPSG:21781','EPSG:4326','CRS:84','EPSG:3857','EPSG:900913']
    bbox_srs:
      - 'EPSG:2056'
    image_formats:
      - image/jpeg
      - image/png
      - image/gif
      - image/GeoTIFF
      - image/tiff
    attribution:
      text: ''
    on_source_errors: raise
    strict: false
    featureinfo_types:
      - text
      - xml
    md:
      title: Gebietseinteilung Auftragskarte
      abstract: WMS Dienst mit Gebieten für Auftragskarte
      online_resource: 'https://www.gis-daten.ch'
      contact:
        organization: GIS Daten AG
        address: Aemaettlistrasse 2
        city: Stans
        postcode: 6370
        country: Switzerland
        phone: +41 (0)41 618 61 12
        email: support@gis-daten.ch
      access_constraints: Dieser WMS ist für interne Zwecke bestimmt
parts:
  coverages:
    bboxnw: &bboxnw
      bbox:
        - 2643483
        - 1171738
        - 2702269
        - 1216819
      srs: 'EPSG:2056'
    bboxow:
      bbox:
        - 2643483
        - 1171738
        - 2702269
        - 1216819
      srs: 'EPSG:2056'
    bboxnwow: &bboxnwow
      bbox:
        - 2643483
        - 1171738
        - 2702269
        - 1216819
      srs: 'EPSG:2056'
    bboxlu: &bboxlu
      bbox:
        - 2630127
        - 1180568
        - 2681764
        - 1237690
      srs: 'EPSG:2056'
    bboxels: &bboxels
      bbox:
        - 2620000
        - 1146000
        - 2724800
        - 1242000
      srs: 'EPSG:2056'
    bboxclip: &bboxclip
      bbox:
        - 2660000
        - 1172000
        - 2680000
        - 1200000
      srs: 'EPSG:2056'
    bboxch: &bboxch
      bbox:
        - 2480000
        - 1062000
        - 2865000
        - 1302000
      srs: 'EPSG:2056'
layers:
  - name: ch.geb_sur
    title: Gebiet Sursee
    sources:
      - ch.gebiet_sur_source
  - name: ch.geb_dag
    title: Gebiet Dagmersellen
    sources:
      - ch.gebiet_dag_source

sources:
  ch.gebiet_sur_source:
        type: arcgis
        http:
           ssl_no_cert_checks: True
        req:
          layers: show:1
          url: >-
            https://gisdaten-ags-01.gisdaten.local:6443/arcgis/rest/services/tn_basis/Auftragskarte_Gebietseinteilung_Dag_Sur/MapServer
          transparent: true
        opts:
          featureinfo: false
        image:
          opacity: 0.5
        supported_srs:
          - 'EPSG:2056'
        coverage: *bboxlu     
  ch.gebiet_dag_source:
        type: arcgis
        http:
           ssl_no_cert_checks: true
        req:
          layers: show:0
          url: >-
            https://gisdaten-ags-01.gisdaten.local:6443/arcgis/rest/services/tn_basis/Auftragskarte_Gebietseinteilung_Dag_Sur/MapServer
          transparent: true
        opts:
          featureinfo: false
        image:
          opacity: 0.5
        supported_srs:
          - 'EPSG:2056'
        coverage: *bboxlu
grids:
  webmercator:
    base: GLOBAL_WEBMERCATOR
  epsg_2056_10000:
    res:
      - 500
      - 250
      - 100
      - 50
      - 20
      - 10
      - 5
      - 2.5
      - 2
      - 1.5
    bbox:
      - 2480000
      - 1062000
      - 2865000
      - 1302000
    bbox_srs: 'EPSG:2056'
    srs: 'EPSG:2056'
    origin: nw
globals:
  srs:
    axis_order_en:
      - 'EPSG:21781'
      - 'EPSG:2056'
  cache:
    base_dir: /mapproxy/cache_data
    lock_dir: /mapproxy/cache_data/locks
    tile_lock_dir: /mapproxy/cache_data/tile_locks
    meta_size:
      - 4
      - 4
    meta_buffer: 80
  image:
    resampling_method: bicubic
    stretch_factor: 1.15
    max_shrink_factor: 4
    paletted: false
    formats:
      custom_format:
        format: image/png
        mode: P
        colors: 32
        transparent: true
        encoding_options:
          quantizer: fastoctree
      image/jpeg:
        encoding_options:
          jpeg_quality: 60